const mongoose = require("mongoose");

const drugSchema = new mongoose.Schema({
  drugImages: String,
  drugName: String,
  type: String,
  responsibleParty: String,
  responsiblePartyCountry: String,
  manufacturer: String,
  manufacturingCountry: String,
  cargoShippingTerms: String,
  priceForeign: String,
  currencyForeign: String,
  convertToUSD: String,
  convertToLBP: String,
  registrationNumber: String,
  registrationDate: Date,
  reviewDate: Date,
  mohCode: String,
  ingredientsAndstrength: String,
  form: String,
  primaryContainerPackage: String,
  agent: String,
  atcCode: String,
  dosageUnitN: String,
  dosageValueN: String,
  dosageUnitD: String,
  dosageValueD: String,
  parentaralCheckbox: Boolean,
  scoreCheckbox: Boolean,
  presentationContentQty: String,
  presentationContainerQty: String,
  contentUnitType: String,
  containerUnitType: String,
  prescriptionAndDispensingCondition: String,
  subsidizationLabel: String,
  douanes: String,
  notes: String,
  chronicCheckbox: Boolean,
  acuteCheckbox: Boolean,
  mentalHealthCheckbox: Boolean,
  essentialCheckbox: Boolean,
  atcRelatedIngredients: String,
  stratum: String,
  cargoShipping: String,
  agentProfitMargin: String,
  pharmacistProfitMargin: String,
  hospitalPriceLBP: String,
  responsiblePartyID: String,
  manufacturerID: String,
});

const Drug = mongoose.model("Drug", drugSchema);

module.exports = Drug;
